spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/companymanager
    username: tedi
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      allow-pool-suspension: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      boot:
        allow-jdbc-metadata-access: false
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
